frequency: 5
sensor_timeout: 0.2
two_d_mode: true
transform_time_offset: 0.0

publish_tf: true

# Sensor sources
imu0: /imu/data
gps0: /gps/fix

# These boolean arrays tell the EKF which parts of the sensor message to use 
# when updating its state estimate. Each index in the array corresponds to one 
# element of the state vector, which is typically ordered like this:
# 1. Position: x, y, z
# 2. Orientation: roll, pitch, yaw
# 3. Linear Velocity: x_dot, y_dot, z_dot
# 4. Angular Velocity: roll_dot, pitch_dot, yaw_dot
# 5. (Optional) Acceleration: x_accel, y_accel, z_accel

# IMU configuration
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true, true, false,
              false, false, false]

# GPS configuration
gps0_config: [true, true, false,
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, false]

# Frame settings       
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map # The frame in which this EKF publishes the robot's pose.